[package]
name = "bms-table-fetch"
version = "0.3.0"
publish = false
edition = "2024"
license = "Apache-2.0"
homepage = "https://github.com/MiyakoMeow/bms-table-mirror"
description = "Fetch BMS table indexes and table data from remote sources"

[lints.rust]
dead_code = "deny"
unused = { level = "deny", priority = -1 }
missing_docs = "deny"

[lints.clippy]
pedantic = { level = "deny", priority = -1 }
allow_attributes = "deny"
allow_attributes_without_reason = "deny"
unwrap_used = "deny"
indexing_slicing = "deny"
pub_use = "deny"
mod_module_files = "warn"

[lib]
name = "bms_table_fetch"
path = "src/lib.rs"

[[bin]]
name = "bms-table-fetch"
path = "src/main.rs"

[dependencies]
bms-table = "0.12"
reqwest = "0.13"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "fs"] }

env_logger = "0.11"
log = "0.4"
anyhow = "1"
url = { version = "2", features = ["serde"] }

clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
toml = "1.1"

chrono = { version = "0.4", features = ["serde"] }
sha3 = "0.10"
