# 配置表来源列表
# - table_list: 远程表列表接口（返回表列表）的对象数组，每项包含 name 与 url
# - add_table: 额外直接添加的表对象数组（无需表列表）
# - disable_table_url: 需要禁用的表页面地址数组（从最终表列表中移除）
# - replace_table_url: 将某个表页面地址替换为新地址（等价或迁移）

table_list = [
  { name = "DARKSABUN", url = "https://script.google.com/macros/s/AKfycbzaQbcI9UZDcDlSHHl2NHilhmePrNrwxRdOFkmIXsfnbfksKKmAB3V65WZ8jPWU-7E/exec?table=tablelist" },
]

disable_table_url = [
  # 在此禁用某些难度表 URL，例如：
  # "https://example.com/old-table"
  # 发狂PMS随机抽选。目前暂不支持反向代理data.json
  "https://pmsdifficulty.xxxxxxxx.jp/subtable/randomselect/randomselect.html",
]

# 添加难度表
# Ereter DP推定表
[[add_table]]
url = "https://bmstable.iidx.org/ereter-dpbms-easy-clear"
tag_order = "2"
tag1 = "DP"
tag2 = "Personal"
[[add_table]]
url = "https://bmstable.iidx.org/ereter-dpbms-hard-clear"
tag_order = "2"
tag1 = "DP"
tag2 = "Personal"
# AI难易度表
[[add_table]]
url = "https://bms.hexlataia.xyz/tables/ai-full.html"
tag_order = "1"
tag1 = "SP"
tag2 = "Personal"
[[add_table]]
url = "https://bms.hexlataia.xyz/tables/ai.html"
tag_order = "1"
tag1 = "SP"
tag2 = "Personal"
[[add_table]]
url = "https://bms.hexlataia.xyz/tables/ai-lite.html"
tag_order = "1"
tag1 = "SP"
tag2 = "Personal"
# Witchart 难度表（魔joy）（魔女个人表）
[[add_table]]
url = "https://mplwtch.github.io/witchart/"
tag_order = "1"
tag1 = "SP"
tag2 = "Self-made Chart Only"
# ぴｃにｃ　aRea（AYhaz PMS难度表）
[[add_table]]
url = "https://yaritaihoudie.fr/table_picnicarea.html"
tag_order = "3"
tag1 = "PMS"
tag2 = "Self-made Chart Only"
# MiKaDo个人难度表
[[add_table]]
url = "https://mikado573.github.io/table.html"
tag_order = "1"
tag1 = "SP"
tag2 = "Self-made Chart Only"
# 連打絡み難易度表
[[add_table]]
url = "https://lets-go-time-hell.github.io/mini-jack/"
tag_order = "1"
tag1 = "SP"
tag2 = "Personal"
# みんな仲良く難易度表
[[add_table]]
url = "https://auno653.github.io/minnanakayoku/"
tag_order = "1"
tag1 = "SP"
tag2 = "Personal"

[[replace_table_url]]
from = "http://ereter.net/dpoverjoy"
to = "https://ereter.net/static/analyzer/json/header.json"
[[replace_table_url]]
from = "https://atharnal.synology.me/diff/table.html"
to = "https://atharnal.github.io/diff/table.html"
